extern Value build_http(void);
extern Value build_time(void);
extern Value build_fs(void);
extern Value build_file_map(void);
extern Value build_random(void);
extern Value build_process(void);
extern Value build_path(void);
extern Value build_encoding(void);
extern Value build_ffi_mem(void);