/* Auto-generated by candlec --pack */
static const char g_source[] =
  "load std.file alias file;\n"
  "load std.math alias math;\n"
  "\n"
  "int main() {\n"
  "    print(file.File);\n"
  "    print(math.PI);\n"
  "    alias h = file.open(\"test/fs/1.candle\", \"rb\");\n"
  "    if (h) {\n"
  "        alias line = file.readLine(h);\n"
  "        print(line);\n"
  "        file.close(h);\n"
  "    }\n"
  "    print(\"file-AOT OK\");\n"
  "    return 0;\n"
  "}\n"
  "";

int interp_run_string(const char *source, const char *filename);

int main(void) {
    return interp_run_string(g_source, "C:\Users\25654\Desktop\Candle\test\fs\1.candle");
}
